spring:
  mvc:
    charset: UTF-8
  servlet:
    multipart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/jpa_lecture
    username: woongblack
    password: woongblack1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create   # 개발용(create/update/validate/none)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8